Fixes policy CMP0135 warning for CMake >= 3.24
ros2/spdlog_vendor pull request #30
Opened 2022-09-09 20:16 UTC by Crola1702

Signed-off-by: Crola1702 <cristobal.arroyo@ekumenlabs.com>

Reference build: https://ci.ros2.org/view/nightly/job/nightly_win_deb/2473/

[This](https://cmake.org/cmake/help/latest/policy/CMP0135.html) warning started appearing on new Windows machines. It’s caused by a new CMake version (3.24) that expects this policy to be set.

This PR sets CMP0135 policy in CMakeLists.txt

CI launch:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17255)](http://ci.ros2.org/job/ci_linux/17255/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11794)](http://ci.ros2.org/job/ci_linux-aarch64/11794/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17735)](http://ci.ros2.org/job/ci_windows/17735/)

2022-09-09 20:37 UTC, clalancette requested changes

2022-09-09 20:37 UTC, clalancette commented on CMakeLists.txt
> +if (POLICY CMP0135)
```suggestion
if(POLICY CMP0135)
```

(this is why CI is failing)

2022-09-12 14:34 UTC, clalancette approved these changes
Looks good with green CI.

2022-09-12 14:36 UTC, Crola1702 commented
New CI_launcher builds with NEW behavior:
* Linux [![Build Status](https://ci.ros2.org/job/ci_linux/17274/badge/icon)](https://ci.ros2.org/job/ci_linux/17274/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11814)](http://ci.ros2.org/job/ci_linux-aarch64/11814/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17755)](http://ci.ros2.org/job/ci_windows/17755/)

2022-09-12 14:37 UTC, merged

2022-12-15 19:31 UTC, Crola1702 commented
@Mergifyio backport humble